#+title: art
Art studies
* Historia da arte
** Japao
*** Literature
**** Murasaki Shikibu
[[https://pt.wikipedia.org/wiki/Genji_Monogatari][Genji Monogatari]]
*** Racismo e eugenia na arte :racismo:eugenia:
***** A redenção de Cam Modesto Brocos.
Nesta pintura sobre tela é possível analisar a relação
de uma mãe mulata segurando seu filho dele mais alva, enquanto
o pai branco ao lado dela observa a criança com orgulho, ao
lado esquerdo da mulher é possível ver sua mãe negra dando graças
pelo filho ter nascido branco.
*** Fascismo
**** Nazism art
***** Directors
****** Leni Riefenstahl
* Art studies
*** Drawing
*** Photography
***** Mapplethorpe
***** Andre Serrano
***** Diane Arbus
*** Manga :japao:
***** Organizado por estetica
***** Ero Guro
******* Authors
******* Suehiro Maru
Triumph des Willens.
[[https://www.youtube.com/watch?v=-2vdFScoPUI][O que e Nazichic?]]
***** Tomboys estética
[[https://www.youtube.com/shorts/fqm0WvYXIj0][youtube short tomboys aesthetics types]]
***** Boys love :historiadahomoafetividade:
O conto de genji
***** Revistas
***** Garo
***** Autores
****** Sanpei Shirato.
*** Quadrinhos
***** Quadrinistas
******* Winshluss
*** Fontes
[[https://www.youtube.com/watch?v=GEw2XVGF_Cw][Alexandre Linck no InteligenciaLTDA:youtube:]]
*** Taxonomia por estetica e conceito
**** Fascismo
***** Frank Miller
****** 300 de esparta. :FrankMiller:
****** O cavaleiro das trevas. :FrankMiller:
Proto fascismo.
**** Violencia e sexo
***** Lost Girls :AlanMoore:
*** Cinema
*** Essays and papers
***** Authors
******* Jacob Geller
[[https://www.youtube.com/watch?v=f4ynPp10jMc][Rationalizing Brutality: The Cultural legacy of the headshot]]
***** Thesis
***** Meta análise
******* Arte na cultura  memetica
A maneira biologica que a cultura evolui e como o neo fascismo surgi de
elementos da cultura pop, e estetica fascista, muitos tracos do fascismo
classico reaparecem nas praticas de movimentos politicos do seculo 21, a direita
delirante reinventa o discurso higienista utilizando-se de teorias da
conspiracao para justicar uma politica publica, como uma vez citado por Olava De
Carvalo que o casamento gay seria nocivo a sociedade pois "quebrava" uma suposta
regra de matrimonio que desembocaria na poligamia e posteriormente na
bestialidade.  Bestial ou degeneracao sao termos frequementemente utilizados
pela direita para se referir a culturas que representam o objeto perseguido,
carnaval e funk frequentemente sao citados como exemplo.  *Cromatismo no neo
fascimo* O conceito autoral de cromatismo nos movimentos politicos descreve a
variancia de radicalizacao dentro de movimentos.  Quando um individuo utiliza o
termo "besta", ele expressa para um publico ideias de odio que podem ser
incubadas e resultar em politicas de perseguicao, censura e exterminio indireto.
******* A instrumentalização da arte em serviço do capital.
***** Art reflections
******* Alex Atala :gastronomia:comunicacao:
[[https://www.youtube.com/watch?v=5qmKeof3Z0k][Alex Atala no Roda Viva]]
*** Intelectuals
- Gilles Lipovetsky ::
