#+title: personal
* Info
* Trabalho
** Portifolio
*** Sobre mim
1. Sou um recém ingressado no mercado de desenvolvimento, busco integrar equipes para criar soluções e produtos
dos quais eu possa sentir orgulho, minhas últimas experiências foram o desenvolvimento de telas e lógica de negócio para projetos
diversos em duas empresas diferentes, me comunico em inglês e alemão, e sou em minha essência de vida um autoditada.

2. Sou um grande entusiasta de TI, faço uso das tecnologias que uso para trabalho
também para a vida pessoal

** Obra
*** Movimento artístico industrial.
- Note taken on [2022-10-03 Mon 17:32] \\
  Manifesto da minha obra
*Soluções de informáticas atreladas à excelência da ciência da computação e da arte,*
*soluções estéticas, para ser eficiente e satisfazer o papel de objeto enquanto*
*em um mundo moderno, é preciso ser estético e eficaz.* As novas tramas e dilemas
do humano moderno devem encontrar oxigênio em novos movimentos culturais
que iram disruptir paradigmas velhos, quebrar o status quo e permitir
que qualquer um possa se ver diante às novas dinâmicas modernas.
A transformação completa do ser humano com as novas tecnologias
faram com que muitos problemas se tornem velhos, a resposta
para inúmeros problemas atuais está no corpo e na fisiologia cérebro
do homem. Para mudar o mundo, é preciso mudar o corpo e a mente fisicamente,
terapias genéticas e mutações ofereceram uma nova janela para o humano.

Seguem alguns valores e pontos estéticos da minha forma.
*** Desconstrução do homem
*** Integração através da expressão artística
** Carreira
*** Cursos
**** TODO ADS
***** Cursos/formações
**** TODO Engenharia da computação
* Dressing
** Bags
*** Dictionary
- Lumper pack bag :
*** Products
**** [[https://jadyvs.ethnicdj.top/index.php?main_page=product_info&products_id=12807][North Face Lumper pack purple label]] :northface:
