#+title: writing/lyrics
** Rebento
Foi fato feito, consumado, posto contra as adversas condições.

Morra, verme infeliz.

Se nasce num sibilo de um passaro divino, desfalece no roncar do cão preto
em meio ao ruido nauseante.

Sofra

Pra finalmente ver nos olhos dele o brasileiro.

** Solipsismo.

Duas partes eternamente almejando o toque,

Colidindo violentamente em busca da imagem de si no olhar de outrem, ressentindo
pelo significado perdido de outrora.

Falanges de um maquinário cruel, banham-se em sangue para sentir a vida dentro
de si própios

** Sem Braços

Espero caminhar pelos sítios longíncuos de meu país, Carregar o olho d'agua com
o orvalho de um alvorecer iterado, Acordar os dias e abrir os pulmões para um
respirar de esperança, Quando nada mais me restar, deitar-me-ei sob a flâmula da
liberdade.

Antes fosse um sonho imaculado, sem ser aviltado por um algoz sorrateiro, Ao
cair da noite esmorece a alma de um anjo antes intocado,

O badalar sincope dentro do peito que soa violação O respirar doloroso de um
órgão quebrado.

Sentir escorrer o gozo amargo dentre os lábios, por ver escapar a razão entre os
finos dedos,

Encher os pulmões para falar uma língua macabra.

Relutar em vão sobre os signos héreges. Em busca de uma mão para impedir o
colosso, que toma de assalto o esboço de um homem inteiro, agora desmembrado.

Flutuou sobre a névoa em ecstase após ouvir o chilro de 10 mil passários.

Sua mente esfumaçada, sua alma repartida, suas barreiras
expandidas, seus pés enraizavam nas cinzas pós inceneração
das vias, deixai entrar o miasma da realidade, convulsionar-vos
a nova razão.

Seus olhos-Depredados,

Seus seios-Extorquidos,

seu corpo-Extraviado.

Sem braços.

** Solilóquio.

** Em todos os lugares eu floresço

Jaz aqui, jazí aqui outrora,
Rasgou um colibri na auróra,

Uma grande massa ululante, gorjear-a uníssono propósito.

Renascer

Zarpar

Cândito olhar

** A incrível passagem do tempo
