:PROPERTIES:
:ID:       a61c9edd-bcf9-435e-8928-d29dd28a52f5
:END:
#+title: writing/books/saga das centelhas
** Saga das centelhas
*** Lorem
**** Antologia
***** Mythos
As 12 centelhas foram as primeiras a nascer após a desfalefação do primeiro
dragão. No primeiro cosmos,as asas e o corpo de Artimur desenharam no universo
as primeiras razões da existência, as bases da magia e o primeiro passo do tempo.
As luzes se puseram em forma, um enorme pentagrama em um espaço suspenso.
Com a passagem do tempo, o espaço se encheu com ecos do primeiro grito dracônico.

Zjian
***** Da magia
Dois planos, dois mundos existem em contraposição, gêmeos que em suas linguagens únicas, representam uns aos outros, alterar e interagir, permite alterar o outro.

Todo ato possui significado duplo, cada face respectivamente representada em seu respectivo plano, linguagens, artefatos e outros artíficios de abstrair um processo, interagir com o outro lado da folha, essa foi a analogia que minha mãe fez para mim na minha primeira lição de formas mágicas.

Existem limites? Qual o tamanho dessa folha que vc descreve?

Os limites são incertos, pouco conhecidos, e o universo é grande demais, o maior na verdade, minha raça esteve aqui desde as primeiras passagens do tempo, mas nossos corpos e nossas mentes exerceram a função de extender e limitar a compreensão das coisas. Somos também fruto de magia, se é assim que deseja chamar, filhos de um "Deus".


***** Dos dragões
****** Artimur
****** Kimbertriam Gorlumail
***** Dos  homens  de Vall`O Silla
****** A fogueira
Dizem que as primeiras estirpes dos homens caminharam pelas
planíces a milênios, ao povoarem as primeiras regiões, recolheram-se os Alhumirini para a Ainquinis
******* O deus azul
O primeiro rei banhou-se no sangue do falso deus, após
desferir um  golpe contra a sua barriga em uma cerimônia
***** Dos Alhumirini.
****** Primeira estirpe
******* Al'Yhim Erinluminas
O arbitro
***** Cronologia
****** *Sistema de contagem do tempo dos Alhumirin***
 1589 Iriuns compoem um Letvna
****** Primeiro céu
    4589 Letvna
 --------------------------->
 ^    ^
 Nascimento de Telaivin
      ^
      Criação do Alhumirin
****** Lorem
****** Hartomel
****** Kaskarathus
****** Limin
**** Xoiah
Irrombia o silêncio e o vazio os prospectores gêmeos,
Uma diádi sonora de timbres oscusos

Dançavam suspensos no espaço,
Duas forças brilhantes disformes,
Misturavam-se em meio a arcos de luz formavam
vitrais cristalizados de matizes esverdeadas, púrpura e rubras,

Dos raios condensendentes sobre as marés cromáticas, brilharam
pedras, circolos flamejantes quentes, de chamas invisíveis,
rosáceas de ossos do universo, olhos abertos, cheios de névoas

Raízes amarelas descendiam as pedras suspenas, ao centro, uma estrela
negra roubava luz dos arredores, e as convertia em estruturas de
pedra branca


**** A mais bela flor Alhumirini
*** Hartomel
*** Kaskarathus
**** Asger Hamerik Tetulias
Os cheiros eram indiscritíveis, o mar de destruição era de perder a vista,
