:PROPERTIES:
:ID:       049cb628-acf9-414a-bca5-b6f4471ce614
:END:
#+title: writing/books/Choramindú
* Infos
** Henrique
1. Henrique sabe dirigir e tem uma paixão por veículos auto motores,
   possui uma coleção grande.
2. Henrique tem muitas posses
** Thomaz
** Sergio
** Vírus capitalista
A subjetivação dos moldes produtivos fez com que a classe trabalhadora criasse
uma prisão de carne individual, o ruir dos direitos nos países asiáticos
possibilitou a completa subversaçãoo da natureza e criou o caminho para a
evolução, em 2042 tivemos o primeir ser humano a não precisar dormir, em
entrevista Robert O'Neil, chinês de nascença repatriado escocês, disse a BBC que
usava 100% de seu tempo para -produzir- artes e trabalhar

* Choramindú
** prelúdio para meninos
        Quando se é pequeno e as dimensões do corpo são aprendidas, testamos
    nossa envergadura sobre os outros, sacamos um gesto, reagimos a uma
    expressão, trocamos figurinhas e rimos pra quebrar o gelo, as vezes numa
    pausa da brincadeira, vemos o reflexo um do outro nos fundos dos olhos.

    "Meu pai é advogado, ele comprou um patinete pra mim!"

    "O meu trabalha dirigindo um caminhão, ele leva coisas paras as pessoas!"

    "Meu pai é professor, ele da aula de música pra crianças"

    João gostava de armas e policiais, fazia de tudo seu instrumento de morte,
    um graveto era uma pistola e um galho arrancado um fuzil, seu pai era
    delegado, Pedro gostava de ninjas e poderes que podia soltar pelas mãos,
    podia ficar invísivel mesmo sendo o garoto de aparência mais destacada, seu
    pai era pastor e detestava as brincadeiras do filho, achava que bruxaria e
    artes de magia negra não eram assuntos para se brincar, Fabrício era o mais
    tímido, gostava de colecionar dinossauros de plástico e amava contar
    histórias inventadas, os três trocavam figurinhas no recreio da escola Dona
    Mária de Fátima na rua do Arouche em Jundiaih. Os meninos se reuniam num
    canto perto do trepa trepa na caixa de areia, as meninas se aninhavam em
    baixo da árvore na pracinha de concreto perto da entrada para as salas de
    aula, elas ficavam dentro de construções de plástico realizando êmulos da
    vida adulta que assistiam em seus lares e nas ruas. O sol surgia sempre
    nesse horário para espantar o frio típico de mês de Junho, os verdes do muro
    encoberto de relva saltavam aos olhos, as brisas gélidas fatiguavam os
    rostos das crianças que corriam e gritavam para preencher o silêncio daquele
    pequeno e modesto bairro residencial, não havia carros ou passantes, apenas
    a escola, algumas senhoras em suas casa levando os trabalhos domésticos, os
    adultos trabalhando, as crianças brincando e aprendendo.

        Ao canto esquerdo do pátio do colégio havia um gira gira desocupado
    chamando um menino segregado dos outros para sentar, as perninhas finas
    desengonçadas iam quase que deslizando timidamente para conversar com este
    único amigo metálico de Otávio, o garoto mexia no seu suspensório antiquado
    enquanto dava pequenas bicudas nos formigueiros em volta do centro do gira
    gira, de longe parecia um fantasminha solitário com sua pele alva e
    aparência frágil.  Resmungava baixinho sozinho: "Hoje eu vou falar pra ele,
    eu vou falar pra ele que eu acho ele feio!", chutava mais forte o
    formigueiro.

    - Eu vou falar pra ele, que se ele não me deixar em paz, eu vou chutar as
      câmeras e morder a perna daquele filha da mãe.

      Fungava e choramingava Otávio num monólogo.

        Beatriz se aproximava às espreitas por trás do menino, ela era quase
      duas
    vezes maior que ele, se projetou como estátua e gritou: "Otávio!", o coração
    dele saltou num susto, esfreguava freneticamente o rosto para tentar
    esconder que estava chorando, o rosto corado e as mangas rotas de lágrimas.

    - Por que esta chorando?

    Perguntou Beatriz séria.

    - Nada, não é nada!

    A menina se sentou em silêncio do lado de Otávio, os dois ficaram sem se
    bicar por alguns instantes, ficaram escutando os gritos e observando as
    outras crianças de longe, Beatriz acomadara o ombrinho dele encostando de
    leve com o seu, esperava ouvir ele começar a falar, umas balançadihnas de
    pernas pra lá, uns matinhos arrancados pra cá, e ele cochichou:

    - Não quero mais.

    - Não quer mais o que?

    - Não quero mais ir pra lá, ver aquelas pessoas, me vestir com aquelas
      roupas, meu pai diz que em breve eu vou voltar, mas eu não quero, no
      começo eu gostava, as outras crianças eram legais, mas eu quero ficar aqui
      na escola.

     Otávio falava e soluçava, os lábios contorcidos, um choro baixinho agudo,
      tentava conter as lágrimas com as mãos, mas não conseguia.

    - Olha, toda vez que você vier pra escola, eu estarei esperando pra gente
      subir o monte, depois da TV, você pode ir em casa, pedir pro seu pai levar
      você, ele vai deixar, deixa que eu falo com ele!

    - Não! Ele não vai deixar, você não pode falar com ele, ele vai ficar bravo,
      ele vai perguntar o que eu vou fazer na sua casa, onde você mora, vai
      ficar bravo comigo por não estar filmando.

    - Mas seu pai gosta de mim, ele já te prometeu que deixaria você da próxima
      vez que viesse, ficar um pouco brincando comigo em casa.

    - É mentira dele, ele já disse isso umas 5 vezes, antes do fim daquele
      seriado, antes de eu terminar aquela outra novela, era pra ser dessa vez,
      mas acharam outra coisa pra eu fazer, ele só me deixou vir aqui porque o
      psicólogo disse pra eu vir, e porque eu não estava indo bem nas gravações.

        Beatriz ficou em silêncio ouvindo aquilo temendo que acabara de notar
      que o menino tinha razão, respirou fundo, Otávio parecia se perder em seu
      olhar, divagava na medida que uma sensação melancólica subia à cabeça,
      respirou fundo e levemente, o mundo se silenciava enquanto às crianças
      voltavam às salas de aula, suas vias aeras estavam limpas após o choro, um
      raio de luz rasga a penumbra do canto do parquinho e acerta bem os olhos
      flamejantes azuis do ator mirim estrela, Beatriz em silêncio assisti
      nascer ali um Otávio que não conhecia, Otávio irrompe o silêncio com o
      hino derradeiro do fim de sua infância

      - E se eu morrese?

        A garota ao ouvir aquilo encheu seu coração de desespero, sentia o peso
        das
      palavras do garoto, mesmo sendo 2 anos mais velha, aquilo assustou tanto
      ela, veio tão de repente que começou marejar os seus olhos e a ofegar.
      Tentou juntar as palavras mas saiu apenas um pequeno soluço em resposta à
      afirmação colossal do pequenino, Otávio esperava uma resposta, assistiu os
      lábios de Beatriz tentar formar uma palavra, esboçou confusão ao não
      receber uma resposta.

      - É isso, direi a ele que vou morrer se ele não para, que eu vou me matar!
        É isso.

        Nem mesmo ele compreendia exatamente o que queria dizer com aquilo, ele
        achava que morrer era como dormir, ou que bastava apenas essa ameaça
        para fazer o seu pai sucumbir e deixa-lo em paz, e se ele dissesse isso
        durante às gravações? Que reação ele causaria?  Se gritasse à midia?
        Isso sim causaria um terror em seu pai, fato é que ele saiu decidido,
        com o espírito restaurado, se sentia vivo e decidido após pensar em
        morrer, levantou abruptamente deixando sua amiga para trás e caminhou
        voltando à sala de aula, Beatriz, em choque permaneceu uns instantes
        estática, mas logo acompanhou o menino.


    Otávio esteve teso ensaiando seu papel de dizer que queria morrer frente ao
    portão da escola esperando seu irmão chegar quando de repente uma melodia
    rouba sua atenção, isso o fez lembrar das aulas de música, do violino, do
    canto, dos amigos do coral, e como sentia falta de sua mãe que cantava para
    ele dormir pequenas melodias tradicionais polacas, suas pernas sinalizavam
    que queria atravessar a rua correndo, algo que ele era esperto o suficiente
    pra entender que era perigoso, mas mesmo assim olhou em volta, não observou
    nada, silêncio pleno, na verdade ele olhora apenas para a direita, não para
    ambos os lados, as linhas de fumaça dos fornos da olaria lembravam um quadro
    que ficava na sala da sua casa, sua mãe que pintara, seus olhos se encheram
    de lágrimas mais uma vez, por lembrar da profunda e tenebrosa ferida que a
    morte de sua mãe deixara, e impetuosamente correu para atravessar a rua
    quase na esperança de encontrar, a rua larga parece eterna, os seus quase
    que se confundiam, num único arroubo ele decidira que seria músico e que
    isso faria sua mãe feliz no céu, mas tragicamente, o outro ator no topo da
    subida mais íngrime da cidade esperara tempo demais para a sua entrada,
    esperara pacientemente para numa ironia divina ou coincidência macabra
    romper seus freios, o caminhão carregado de madeiras que abasteceria a
    olaria naquela tarde descia velozmente a rua sem fazer muito barulho, pois
    seu motor estava desligado e Otávio estava atônito e desatento, foi certeiro
    o impacto, acertou a criança ao meio e pintou as ruas uma das cores do seu
    país de origem, suas roupas e restos ocuparam a rua finalizando o cenário
    infernal naquele pequeno bairro pacato em Jundiaih, a primeira a ver e
    processar o que havia acontecido era Beatriz, que em instantes entendeu,
    reconheceu o corpo pelos sapatos vermelhos e shorts azuis, encheu o bairro
    com um grito de desespero absoluto, ficou branca e desmaiou.

** Thomas

        Ao divagar andando pela cidade numa tarde no meu horário de almoço me
    deparo com uma casa opulente, uma arquitetura bonita e moderna, num bairro
    classe média alta perto do meu trabalho, passo lentamente, entortando
    completamente a cabeça tentando enquadrar a visão daquele lugar críptico que
    parecia despertar em mim as mais profundas sensações a respeito de mim,
    neste momento eu escutava uma playlist que montei com músicas escolhidas do
    Led Zeppelin, uma coleção de momentos da minha adolescência onde eu
    frequentemente me via nessa sensação doce, de ser branco e poder fazer
    coisas de branco, morar em Jundiaí, ter uma narrativa melo dramática sobre
    sair do armário pros meus pais, fumar maconha no meu quarto escutando rock
    (música de gente branca), viver um romance com alguém bonito (branco com
    olhos claros), frequentar festas noturnas e poder gozar minhas habilidades
    artísticas que meus pais financiaram. Fui trazido de volta a esses
    pensamentos depois de provar o contato virtual efêmero de um boy fatale que
    eu conheci tempos atrás, eu acho que ele é exatamente isso que eu descrevi
    nessa pantomima racista e sem graça, pelo menos eu acho que sim, uma coisa é
    certa, todos os branquelos que eu conheci tem famílias mais fodidas e mais
    quebradas do que a minha (que nem é tanto assim), as vezes eu acho que se eu
    fosse 100% preto eu pelo menos teria uma razão mais clara do que pelo o que
    lutar, em vez de ser atraído à coisas macabras só quando estou entediado.

    Lógico que essa não é minha realidade, não é como se fosse ruim, mas eu sou
    um figurão forjado numa família retalhada e complexa que aprendeu a gozar
    num fundo de uma casa em cosntrução. Os gritos sem sentido desse mundo não
    escapam da minha cabeça, é doce e salgado ao mesmo tempo, uma ambivalência
    que parece uma piada divina de mau gosto, as coisas ainda estão mal
    compreendidas por mim, pelo menos eu sinto isso.

        Agora sou assalariado, vou aproveitar a normalidade e ficar sonhando com
    as coisas razas.

** Henrique

        O homem da casa de vidro, era assim que o flanelinha da praça acima
      chamava o pai de Henrique, toda vez que ele o via, gritava: "Oh homem da
      casa de vidro! Oh doutor", Sérgio queria  morrer quando escutava isso, ele
      odiava  encontrar  aquele rapazinho no horário de almoço, mas mesmo assim
      não  conseguia destrata-lo, apenas reclamava com a família na mesa de
      jantar,  Henrique, no banco de traz, observava o flanelinha de longe, toda
      vez que ele se aproximava da janela do carro de seu pai gingando malandramente Henrique levantava o
      vidro de reflexo, pois algo sobre o cheiro do trabalhador que passou o dia
      sob o sol quente o incomodava, olhava por alguns segundos, pensava o que
      fazia o homem, não entendia o porquê ele tanto atrapalhava, antes
      sentia indignação, pensava sobre e comentava na roda de amigos no colégio:
      "Aquele cão idiota repete a mesma coisa todos os dias, parece que o noia
      chapou tanto por tanto tempo que ficou retardado" Exclavama ele, enquanto
      seus amigos adicionavam observações sobre o estado da praça acima que
      estava "enpesteada" de noias, o comportamento rotineiro daquele homem de
      alguma maneira fascinava o menino depois de tanto observar e se deparar
      com aquela mesma situação, todo dia, toda a tarde quando eles passavam
      ali, o homem vinha entoando as mesmas frases, o que ele esperava com isso
      afinal? Era um teatro que seu pai e o flanelinha executavam
      exaustivamente, mas logo após as falas serem proferidas: "Desculpa amigo,
      to sem nota hoje, toma aqui essa moeda" e "Obrigado doutor, Deus te
      abençoe" os fundos olhos azuis logo sinalizavam tédio após o pai se
      desvincilhar do pedinte, nesse momento o rapaz intromissor sempre
      comentava: "Queria eu ter nascido com esse olhar! Minha filha vive
      querendo comprar aquelas lentes pra ficar igual a você", o garoto sorria
      sem graça abobadamente, o sorriso esvasnecia, logo tateava impacientemente
      o seu smarphone, dedilhava os botões da sua jaqueta, enrolava os dedos nos
      seus cabelos lisos e via os fios se alinharem novamente ao soltar.

      Ao cair no enjoo característico de um jovem impaciente, sua mente divagava
      com o movimento do carro pelas ruas da cidade.

        "Talvez eu devesse tentar falar com ele, queria ter tido mais alguns
        minutos, se eu tivesse teria o convencido de ficar, quem ele pensa que
        é? O que eu estou fazendo afinal?  Por que insisto tanto? Me diverte, é
        essa a resposta, ele me diverte, após o primeiro contato visual com
        aqueles olhos afiados, geralmente eles cedem nessa parte, mas ele não
        cedeu, estava decidido a não cair em cima de mim, mesmo tendo claramente
        sido abalado. Sob este sol de rachar, fico agora pensando nisso!",
        exclamou e riu baixinho deslizando no banco do carro.  "Essa gente pobre
        é engraçada, parecem os mais orgulhosos de todos, parecem que eles tem
        orgulho de ser o que são, não os culpo, afinal é nobre resistir e lutar
        em condições adversas, mas eu não consigo entender o que faz um homem
        repetir e agir de maneira estranha essa coisas, eu sou belo, ele até que
        é bonito, mesmo tendo a única oportunidade que ele teria na vida  de
        ficar com um modelo, ele rejeitou, que ego ele teria pra evitar isso?
        Naquela hora, ou outra hora, escondido seja lá aonde, alugaria um
        apartamento só pra isso um mês me divertindo com ele, mas ele me
        rejeitou. Essa gente, eu não entendo essa gente", ria internatamente
        segurando o riso. "Aquele cão também, continua fazendo a mesma coisa
        desde que quando eu era criança, seus olhos já pioraram, ele mal
        enxerga, por que ele não busca ajuda? Um trabalho, eu não sei, eu não
        entendo."


       "Lembra o que te falei?" Perguntou Sérgio calmamente.
       "O que?" Respondeu Henrique fingindo não entender.

       "Dessa vez você vai ficar ali dentro, não há como te expulsarem desse
      lugar, se decidir implicar, isso vai dificultar mais ainda a sua vida"
      Henrique desviou da frase como se não tivesse escutado, o pai silencioso e
      meditativo, parecia confuso e perturbado com as circunstâncias, não
      conseguia entender o comportamento do filho como o filho não entendia o do
      flanelinha, parecia que ele tinha que agir daquela maneira, fazia por
      capricho, era a maneira de ambos matarem o tempo e o tédio que consegue
      ser mais cruel que a própia fome. O garoto pegou sua bolsa, respirou fundo
      irritado e saiu do carro caminhando em direção ao colégio

** Haloween
As fumaças subiam aos céus na medida que os meninos esperavam.
** O Revanchismo
A redescoberta de civilizações já a muito tempo extintas em território nacional
fez com que surgisse um movimento de identidade nacional e de soberania
