:PROPERTIES:
:ID:       63d74c35-9cc3-4346-afe9-da7afeb3dbaa
:END:
#+title: writing/diary
* Sonhos
Coletânea de todos os sonhos que eu já tive
*** Jundiaí dos sonhos
**** Festival de música
**** Conglomerado de moradas em prédio.
**** Cidade suspensa.
**** Estação nos céus.
*** Campo Limpo dos sonhos
**** Arvore de natal
**** Bairros
**** Pedra na caixa d'água
*** Dádio
**** Blood and order
*** Jardim
*** Morato dos sonhos
**** Montanha de casas com sempre a mesma parede faltando apontando para um vale, feito uma sacada de apartamento.
*** São Paulo dos sonhos
**** Prédio armazém do Theatro Municipal.
***** Minczuk
**** Sala São Paulo.
**** Estações suspensas.
**** Paulista se misturando com a Sé
1. Praças de venda popular com galerias
   parelelas à paulista.
**** Parque de diversões
*** Crime castigo
* Diario
<2022-07-10 Sun>
Isso que tenho em mente quando penso na minha relacao com meus familiares agora,
me sinto um pouco pressionado por me sentir capaz de ajudar todos os meus
familiares com suas mazelas, minha mãe, meus avós e minha prima sãos as pessoas
que eu mais penso sobre. Levar a cura a eles, a solução, a dissolvição da dor, o
ato de cuidar é mais uma empreitada intelectual minha em relação ao mundo, me
afundar na dor alheia para estudar as dinâmicas profundas desse mundo.
<2022-10-04 Tue>
        Torpor

    Me perdi depois da serie de eventos dos ultimos meses, me afastei do
Pedro, precisei achar outra consciência, e vivo me enfiando em questões e
trabalhos, me sinto um pouco paralisado por não conseguir atacar esse monstro
que é as minhas vontades e ambições, preciso facilitar as coisas e focar, há
muito o que eu quero fazer, mas preciso saber como destrinchar o problema em
partes menores.  Costumo pensar assim, primeiro vem o financeiro, planejar
corretamente minha carteira de investimentos depois organizo meus trabalhos,
Studio e khanum, agora vem o organizacional para o futuro, preciso arquitetar
meu portifolio, inicar alguns projetos e ver alguns certificados ou cursos,
agora vem os hobbies, nessa parte eu me perco completamente, é simplesmente
muito denso, preciso organizar com calma.
- Note taken on [2022-10-04 Tue 01:20] \\
  Minha conclusão é essa! Vou ir a feira e trabalhar
    Processo de cura
    Vou tentar resumir numa agenda simples, vou fazer uma lista do que eu tenho que
na feira, organizar os trabalhos da khanum e studio, preciso fazer isso essa semana.

<2022-10-04 Tue>
    Criação
 Estou iniciando meus planos para aprimoramento da minha condição, hoje vai ser um dia excepcionalmente produtivo, vou encontrar os pedaços de mim que estão perdidos.

 <2023-05-10 Wed>

 À minha própia maneira.

    Lutar constantemente contra a maré social da vida, contra as imposições numa
 espécie de grito de auto imposição, querendo assim projetar uma imagem de mim
 mesmo ainda incerta, é algo extremamente contraditório, como Narciso
 construindo um mundo de retalhos de espelhos e reflexos que não se viram para
 si e mesmo assim tentar reconhecer nessa amalgama a sua própia imagem.

    Esse excerto que escrevi, creio que expressa perfeitamente uma natureza
conflituosa minha, uma crise identitária onde após desenhar todos os meus
gostos, personalidades e ideiais, não consigo ainda me ver, a mesma mão que
constrói tenta destruir a minha própia imagem, como se eu me odiasse, como se eu
tentasse envolver o mundo em minha narrativa de problemas para fugir delas. Não
faz sentido.
* Trips
** <2024-03-29 Fri>Primeira trip com psilocibina
