:PROPERTIES:
:ID:       06bc2dfd-1e39-44c1-83b9-5882d7c69b89
:END:
#+title: writing/books/knauer
** Knauer
Acordou às pressas, correndo atrás de algo que nem sabia o que era exatamente,
mais um pássaro havia arrebentado a janela de seu enorme mausóleu negro, "Será
que ficaram cegos?", se perguntou o jovem Knauer, ao ficar teso e recuperar os
sentidos defronte ao vidro arrebentado, as gotas de uma chuva fria o pinicava
como milhares de agulha, era uma garoa pequena, numa noite qualquer, em mais um
dia na vida daquele jovem burguês. Logo serão repostas, logo  esqueceu ignorou o
que havia acontecido, ao sair de seu quarto buscando algo para entreter a mente
agora que seu sono havia sido interrompido, se deparou com o corvo agonizando no
chão espatifado, estava com suas asas quebradas.  Knauer ficou ali observando o
animal, deixando sua mente encher e esvaziar com pensamentos que iam e vinham,
logo compadeceu com a dor do pássaro e o recolheu do chão, levou-o até a sala de
serviços e preparou um leito rudimentar com alguns pedaços de madeira e panos
limpos da cozinha, naquela noite calma, ao deslizar pelo salões do palecete de
sua família, com o corvo encaixotado em seus braços, é quase como se as paredes
ecoassem os pensamentos dele e do pássaro, Knauer com seu olhar vazio e
sepulcral, e a criatura com olhos brilhantes e curiosos fitando a face do jovem.
*** Ao nascer
"Ao nascer nos tornamos rios, por definição só existimos se nos movimentarmos,
líquidos buscando serem sólidos, sólidos para impedir a oscilação maldita da
vida que nos faz perder quem amamos e o que gostamos" dizia Alexei enquanto
acompanha Knauer até à igreja, Knauer ouvia Alexei filosofar sobre a sua
condição e as verdades do universo se entretia e deixava o fascínio o guiar.
*** Parte II A descida até o inferno
- Uma cabeça cai na calçada da igreja, ao quicar duas vezes e estarrecer quem ali
  estava, ficou imóvel, quase que fitando as pessoas horrorizadas que estavam ao
  pé da catedral, dois jovens soldados cortaram a esquina esbaforidos em
  êxtase,  seguiam chutando a cabeça do padeiro, que a poucos momentos
  descansava no seu almoço após fechar a padaria. Os soldados estavam tomados
  por um êxtase assustador, sentiam um prazer enorme em correr semi despidos,
  apenas com suas calças atrás do membro morto, uivavam ao mesmo tempo que riam,
  pareciam diabretes que saíram dos vitrais e levaram o pandemônio à praça central.
  Os moradores assistiam perplexos, alguns choravam escondido, ninguém ousava mexer
  um só musculo após testemunharem tudo o que o novo general havia feito.
*** Yan
"Não faremos, você sempre me perguntou o porquê, o mundo parece já ter esquecido
das leis e de como as coisas eram, eu sempre estive na sarjeta, mesmo assim
existiam regras, tudo anda confuso, eu poderia simplesmente abrir mão de tudo e
aproveitar o que restou desse lugar, não vou a lugar nenhum mais, não tem mais
como, passei a vida tentando, mas agora tudo acabou, provavelmente morreremos
este ano, muitos que eu conheço já morreram, estamos encurralados, corpos pra
todo lado, e você ainda olha pra mim depois de todo esse tempo, sabendo quem eu
sou e o que eu fiz, pedindo pra que eu foda com você? Sua esperança agora é
curtir o que sobrou das riquezas da sua família esperando uma bomba cair sobre
sua cabeça? Olha Knauer, o que ainda me resta é você, e mesmo que a morte pareça
certa não podemos" Knauer esteve paralisado ouvindo tudo aquilo, recuperando os
sentidos enquanto sua cabeça girava mil vezes.  "Eu gosto de você Yana, gosto de
verdade, e sinto que você sera a última coisa que me acontecerá na vida, não sei
o que fazer, não há o que fazer, estou esperando a morte"
*** Os artistas
  "Sou só mais um gritante"

- Aquele performante, o que ele quer afinal? Conquistar o que?
- Eu realmente não sei, talvez não seja sobre conquista.
** Presença

[[https://www.youtube.com/watch?v=jO3KC_mvE74][Skinamarink LOOOOOOOOP]]

~ certeza de ter uma reviere onde o Pedro representava uma presenca absoluta de
algo tao rudimentar a minha existencia que me lembrava a sensacao infantil de
ser completo e sem problemas, caminhavamos nesse mundo de sonhos ao som de Venus
do Holst, enquanto eu me sentia em paz apos dias de batalhas e rotina ~

~ Presence do Led Zeppelim comecou a reflexao sobre essa sensacao, aquele disco
que apareceu como uma aparicao uncanny de algo que n deveria ser encontrado no
momento que foi, colocou e cheque boa parte da normalidade da minha rotina, tipo
o monolito de Pathologic ou Uma Odisseia no espaco, a presenca de algo, a
abstracao desse conceito sobre as relacoes humanas e o solipsismo do existencial
absurdo~

"Aquele obelisco edificado sobre às nossas cabeças, esteve entrépido e gélido o
tempo todo enquanto eu tentei e falhei, abriria diante de mim ainda? Antes
quisera o fim, o fim consegui, veio até mim e em seguida ele, nunca o tinha
visto antes, é como se eu só o notasse depois que saí de casa naquele dia,
quando as coisas começaram a acontecer. Logo senti sua presença, me encheu a
primeira vez que o vi, depois das primeiras palavras trocadas, não paramos de se
falar, conversar e andar juntos até semana passada, já faz uma semana, num
periodo contíguo de 4 meses, uma fase que ele foi a minha vida enquanto, o mundo
à nossa volta simplesmente adoecia e dava sinais de que viria a óbito, duas
certezas retumbantes dentro de mim, a de que ele existe e de que tudo acabaria.
Estive todo esse tempo tentando desaparecer, explorar no negativo das coisas uma
forma resolução final, mas a vida não permitiu eu seguir, ela não cessava, e
logo quando tudo surge diante de mim, a certeza de amar, ele desaparece.  Aquilo
apareceu, simplesmente apareceu, as pessoas ficaram perplexas, a guerra chegou,
achavamos que era uma arma que nos mataria, mas não era, logo o absurdo no chão
tomou as atenções dos absurdos nos céus"

** mecanismo de Antikythera.
Objetos arqueológicos que demonstram que mesmo numa sociedade tecnológica e
avançada, a grande verdade é que Deus existe e o inferno também, no limiar da
aniquilação absoluta a vila de Santa Lacrese deve encarar a invasão de um
exército, acontecimentos sobre naturais, o abandono completo da esperança,
frente a tudo isso o jovem Knauer encontra um romance e decide surfar qualquer
onda pra manter aquilo que provavelmente vai ser pra ele a última coisa de sua
vida.


1. num cenário onde a civilização evoluiu muito e explorou as galáxias, se Deus
   e o Diabo existirem eles se tornam as maiores ameaças à raça humana.
