:PROPERTIES:
:ID:       4faca5ab-9290-4ae1-9c91-069c8d452fb9
:END:
#+title: economics/finance
* Concepts
** GAAP general accepted accounting principles
* Dictionary
** Indicadores
*** EBITDA
*** ROE
#+begin_src latex

roe  = (netincome/revenue) * (revenue/average total assets) * (average total assets/shareholders equity)

#+end_src
*** ROCE
*** ROA
*** RORE
*** Underwrinting
*** Sinistralidade
*** P/VPA
Valor patrimonial por ação.
** Termos
*** Dividendos
**** Data com
**** Data Ex
**** Data de pagamento.
*** Tag along
[[https://en.wikipedia.org/wiki/Tag-along_right][wikipedia-tag along]]
"Tag Along é uma ferramenta de segurança garantida aos acionistas minoritários de uma companhia, permitindo que tais acionistas deixem a sociedade caso o controle da empresa passe para um novo investidor, que até então não tinha participação no negócio." - Suno
[[https://www.suno.com.br/artigos/tag-along/][suno-tag along]]
*** Efeito Lindy
*** OTC
What Is an Over-the-Counter (OTC) Derivative?
An over-the-counter (OTC) derivative is a financial contract that does not trade on an asset exchange, and which can be tailored to each party's needs.

A derivative is a security with a price that is dependent upon or derived from one or more underlying assets.
[[https://www.investopedia.com/ask/answers/052815/what-overthecounter-derivative.asp#:~:text=An%20over-the-counter%20(OTC)%20derivative%20is%20a,one%20or%20more%20underlying%20assets.][investopedia-OTC]]
** Demonstrações financeiras
** Tipos de ações
    *Tickers*
- *sufixo 3* Ordinárias:garantem direito a voto
- *sufixo 4* Preferenciais:possuem preferência no recebimento de dividentos.
- *sufixo 11* Unit: conjunto de ações ordinárias
* markets
The types of markets and what rules them, different kinds of markets
may vary in nature and what effects
the businesses.
** Agro market
** Art market
*** Master works
Avant garde block chain system to
break art artefacts into small shares
