:PROPERTIES:
:ID:       3ed2a23f-5706-40f2-b9a8-75530b375edf
:END:
#+title: cooking🍳/receitas
* Pães
** Fermentação natural
*** Pão de milho com fermentação natural
Proporção da receita: 50% de fermentao natuarl em relação a farinha

180g de fermento natural alimentado, é possível alimentar o fermento na *noite*
anterior do uso da *manhã*

Triture 100g de milho verde com 100ml de leite

Misture numa tigela 360g de farinha branca, 30g de fuba de milho amarelo, 60g de
açúcar e 4g de sal.

Após misturar adicione um ovo batido e 180g de fermento natural alimentado.

Sove a massa até o ponto de véu e deixe  descansar numa tigela untada com óleo
até dobrar o tamanho.

*** Pao de fermentacao natural
[[https://www.youtube.com/watch?v=bbv_P8bpvbg][Pao de fermentacao natural]]
** Tipos de pré fermentos
[[https://www.youtube.com/watch?v=ElJFy8ACwEA][Yeasted preferments explained]]
* Ratatoulle
* Paella
* Saladas
** Caesar salada
1. Ovos bem frios
2. Mostarda de Djon
3. Azeite de Oliva
4. Alho
5. Limao siciliano
6. Aliche
7. Queijo parmesao
8. Vinagre de vinho
9. Alface tipo romana
10. Pão amanhecido
* Massas
** Ramen
** Pasta
 - 1 etto per egg and one egg per person.
* Molhos
** Pesto.
** Hollandaise.
* Arroz
* Doces
** Bolos
*** Sabiosa
[[https://www.youtube.com/watch?v=EbgAa1LF-Mg][Sabiosa:PaollaLindaPerfeita:]]
* Snacks
** Barras de cereal
[[https://www.youtube.com/watch?v=rtwlRPBrGIM][video da receita]]

*Ingredientes*

1. xícara de granola (pode ser de marcas diferentes e composta de diferentes grãos para maior nutrição)
3. bananas maduras
2. colheres de sopa de mel

*Utensílios*

1. forma de 15 cm de largura e 25 cm de comprimento

*Preparo*

 1. Unte a forma com óleo

 2. Assar em forno pré aquecido em 200 graus entre 15 e 20 minutos

* Cereais
** Granola
[[https://www.youtube.com/watch?v=OHxOQDGon7Q][Receita da paola]]
• 2 xícaras (chá) Aveia em flocos
• Açúcar demerara
• ¼ xic. (chá) de Açúcar de coco
• 1 xícara (chá) Castanhas de caju torrada sem sal
• 1 colher (sopa) de Sementes de linhaça
• 1 colher (chá) de sal marinho
• 2 colheres (sopa) de gergelim
• ½ xícara (chá) de Mel
• ½ xícara (chá) óleo de soja ou coco
• ½ colher (chá) de essência de baunilha
• 10 unidades ameixa
• banana seca

*Preparo*

- Pré aquecer forno a 160 ou 180 graus
